use std::{fs, path::Path};

use serde_json::{Map, Value, json};

use crate::{
    error::{Error, Result},
    ir::{Action, ClientSpec, Operation},
};

pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    pub fn write(spec: &ClientSpec, output_dir: &Path) -> Result<()> {
        fs::create_dir_all(output_dir).map_err(|source| Error::CreateDir {
            path: output_dir.to_path_buf(),
            source,
        })?;

        let types_path = output_dir.join("types.ts");
        let client_path = output_dir.join("client.ts");

        fs::write(&types_path, Self::types(spec)).map_err(|source| Error::WriteFile {
            path: types_path,
            source,
        })?;
        fs::write(&client_path, Self::client(spec)).map_err(|source| Error::WriteFile {
            path: client_path,
            source,
        })?;

        Ok(())
    }

    pub fn types(spec: &ClientSpec) -> String {
        let mut out = String::from(
            "/* eslint-disable */\n// Generated by asyncapi-mqtt. Do not edit manually.\n\n",
        );

        for operation in &spec.operations {
            out.push_str(&format!(
                "export type {}TopicParams = {};\n\n",
                pascal_name(&operation.name),
                topic_params_type(operation)
            ));
            out.push_str(&format!(
                "export type {} = {};\n\n",
                operation.payload_type_name,
                schema_to_ts(&operation.payload_schema, 0)
            ));
        }

        out
    }

    pub fn client(spec: &ClientSpec) -> String {
        let mut out = String::from(
            "/* eslint-disable */\n// Generated by asyncapi-mqtt. Do not edit manually.\n\n",
        );
        out.push_str("import mqtt, { type IClientOptions, type IClientPublishOptions, type IClientSubscribeOptions, type MqttClient } from \"mqtt\";\n");
        out.push_str("import Ajv, { type ValidateFunction } from \"ajv\";\n");
        out.push_str("import type {\n");
        for operation in &spec.operations {
            out.push_str(&format!(
                "  {}TopicParams,\n  {},\n",
                pascal_name(&operation.name),
                operation.payload_type_name
            ));
        }
        out.push_str("} from \"./types\";\n\n");

        out.push_str(&schemas_block(spec));
        out.push_str(CLIENT_RUNTIME);
        out.push_str(&publish_block(spec));
        out.push_str(&subscribe_block(spec));
        out.push_str(CREATE_CLIENT_BLOCK);
        out
    }
}

fn pascal_name(name: &str) -> String {
    crate::utils::to_pascal_case(name)
}

fn topic_params_type(operation: &Operation) -> String {
    if operation.topic.parameters.is_empty() {
        "Record<string, never>".to_string()
    } else {
        let fields = operation
            .topic
            .parameters
            .iter()
            .map(|parameter| format!("  {}: string | number | boolean;", parameter.name))
            .collect::<Vec<_>>()
            .join("\n");
        format!("{{\n{fields}\n}}")
    }
}

fn schema_to_ts(schema: &Value, indent: usize) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str)
        && let Some(name) = reference.strip_prefix("#/messages/")
    {
        return format!("{}Payload", pascal_name(name));
    }

    match schema.get("type").and_then(Value::as_str) {
        Some("object") => object_schema_to_ts(schema, indent),
        Some("array") => {
            let item_type = schema
                .get("items")
                .map(|items| schema_to_ts(items, indent))
                .unwrap_or_else(|| "unknown".to_string());
            format!("{item_type}[]")
        }
        Some("string") => string_schema_to_ts(schema),
        Some("number") | Some("integer") => "number".to_string(),
        Some("boolean") => "boolean".to_string(),
        Some("null") => "null".to_string(),
        _ => "unknown".to_string(),
    }
}

fn object_schema_to_ts(schema: &Value, indent: usize) -> String {
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        return "Record<string, unknown>".to_string();
    };

    let required = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .filter_map(Value::as_str)
                .collect::<std::collections::BTreeSet<_>>()
        })
        .unwrap_or_default();

    let base = " ".repeat(indent);
    let child = " ".repeat(indent + 2);
    let mut fields = Vec::new();
    for (name, property_schema) in properties {
        let optional = if required.contains(name.as_str()) {
            ""
        } else {
            "?"
        };
        fields.push(format!(
            "{child}{}{}: {};",
            quote_property_name(name),
            optional,
            schema_to_ts(property_schema, indent + 2)
        ));
    }

    format!("{{\n{}\n{base}}}", fields.join("\n"))
}

fn string_schema_to_ts(schema: &Value) -> String {
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        let variants = values
            .iter()
            .filter_map(Value::as_str)
            .map(|value| format!("{value:?}"))
            .collect::<Vec<_>>();
        if !variants.is_empty() {
            return variants.join(" | ");
        }
    }

    "string".to_string()
}

fn quote_property_name(name: &str) -> String {
    if is_identifier(name) {
        name.to_string()
    } else {
        format!("{name:?}")
    }
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(first) if first == '_' || first == '$' || first.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn schemas_block(spec: &ClientSpec) -> String {
    let mut out = String::from("const schemas = {\n");
    for operation in &spec.operations {
        out.push_str(&format!(
            "  {}: {},\n",
            operation.name,
            serde_json::to_string_pretty(&normalize_schema(&operation.payload_schema))
                .expect("schema serialization should not fail")
                .replace('\n', "\n  ")
        ));
    }
    out.push_str("} as const;\n\n");
    out
}

fn normalize_schema(schema: &Value) -> Value {
    match schema {
        Value::Object(map) => {
            let mut out = Map::new();
            for (key, value) in map {
                out.insert(key.clone(), normalize_schema(value));
            }
            Value::Object(out)
        }
        Value::Array(items) => Value::Array(items.iter().map(normalize_schema).collect()),
        Value::Null => json!({}),
        _ => schema.clone(),
    }
}

fn publish_block(spec: &ClientSpec) -> String {
    let mut out = String::from("function createPublishApi(runtime: ClientRuntime) {\n  return {\n");
    for operation in spec
        .operations
        .iter()
        .filter(|operation| operation.action == Action::Send)
    {
        out.push_str(&format!(
            "    async {}(params: {}TopicParams, payload: {}, options: IClientPublishOptions = {{}}): Promise<void> {{\n",
            operation.name,
            pascal_name(&operation.name),
            operation.payload_type_name
        ));
        out.push_str(&format!(
            "      runtime.validate(\"{}\", payload);\n",
            operation.name
        ));
        out.push_str(&format!(
            "      const topic = buildTopic({:?}, params);\n",
            operation.topic.template
        ));
        out.push_str(&format!(
            "      await runtime.publish(topic, payload, {{ qos: {}, ...options }});\n",
            operation.qos.unwrap_or(0)
        ));
        out.push_str("    },\n");
    }
    out.push_str("  };\n}\n\n");
    out
}

fn subscribe_block(spec: &ClientSpec) -> String {
    let mut out =
        String::from("function createSubscribeApi(runtime: ClientRuntime) {\n  return {\n");
    for operation in spec
        .operations
        .iter()
        .filter(|operation| operation.action == Action::Receive)
    {
        out.push_str(&format!(
            "    {}(params: {}TopicParams, handler: (payload: {}, topic: string) => void, options: IClientSubscribeOptions = {{}}): () => void {{\n",
            operation.name,
            pascal_name(&operation.name),
            operation.payload_type_name
        ));
        out.push_str(&format!(
            "      return runtime.subscribe({:?}, params, \"{}\", handler, {{ qos: {}, ...options }});\n",
            operation.topic.template,
            operation.name,
            operation.qos.unwrap_or(0)
        ));
        out.push_str("    },\n");
    }
    out.push_str("  };\n}\n\n");
    out
}

const CLIENT_RUNTIME: &str = r#"export type CreateClientOptions = {
  url: string;
  mqttOptions?: IClientOptions;
  validate?: boolean;
  ajv?: Ajv;
};

class ClientRuntime {
  private client?: MqttClient;
  private readonly ajv: Ajv;
  private readonly validators = new Map<string, ValidateFunction>();

  constructor(private readonly options: CreateClientOptions) {
    this.ajv = options.ajv ?? new Ajv();
  }

  async connect(): Promise<void> {
    if (this.client?.connected) {
      return;
    }

    this.client = mqtt.connect(this.options.url, this.options.mqttOptions);
    await new Promise<void>((resolve, reject) => {
      this.client?.once("connect", () => resolve());
      this.client?.once("error", reject);
    });
  }

  async end(): Promise<void> {
    if (!this.client) {
      return;
    }

    await new Promise<void>((resolve, reject) => {
      this.client?.end(false, {}, (error?: Error) => {
        if (error) {
          reject(error);
          return;
        }
        resolve();
      });
    });
    this.client = undefined;
  }

  validate(operationName: keyof typeof schemas, payload: unknown): void {
    if (this.options.validate === false) {
      return;
    }

    let validator = this.validators.get(operationName);
    if (!validator) {
      validator = this.ajv.compile(schemas[operationName]);
      this.validators.set(operationName, validator);
    }

    if (!validator(payload)) {
      throw new Error(`Invalid payload for ${operationName}: ${this.ajv.errorsText(validator.errors)}`);
    }
  }

  async publish(topic: string, payload: unknown, options: IClientPublishOptions): Promise<void> {
    const client = this.requireClient();
    await new Promise<void>((resolve, reject) => {
      client.publish(topic, JSON.stringify(payload), options, (error?: Error) => {
        if (error) {
          reject(error);
          return;
        }
        resolve();
      });
    });
  }

  subscribe<TPayload>(
    topicTemplate: string,
    params: Record<string, string | number | boolean>,
    operationName: keyof typeof schemas,
    handler: (payload: TPayload, topic: string) => void,
    options: IClientSubscribeOptions,
  ): () => void {
    const client = this.requireClient();
    const topic = buildTopic(topicTemplate, params);
    const listener = (receivedTopic: string, message: Buffer) => {
      if (receivedTopic !== topic) {
        return;
      }

      const payload = JSON.parse(message.toString()) as TPayload;
      this.validate(operationName, payload);
      handler(payload, receivedTopic);
    };

    client.on("message", listener);
    client.subscribe(topic, options);

    return () => {
      client.off("message", listener);
      client.unsubscribe(topic);
    };
  }

  private requireClient(): MqttClient {
    if (!this.client) {
      throw new Error("MQTT client is not connected. Call connect() first.");
    }
    return this.client;
  }
}

function encodeTopicParam(value: string | number | boolean): string {
  return encodeURIComponent(String(value));
}

function buildTopic(template: string, params: Record<string, string | number | boolean>): string {
  return template.replace(/\{([^}]+)\}/g, (_, key: string) => {
    if (!(key in params)) {
      throw new Error(`Missing topic parameter: ${key}`);
    }
    return encodeTopicParam(params[key]);
  });
}

"#;

const CREATE_CLIENT_BLOCK: &str = r#"export function createClient(options: CreateClientOptions) {
  const runtime = new ClientRuntime(options);

  return {
    connect: () => runtime.connect(),
    end: () => runtime.end(),
    publish: createPublishApi(runtime),
    subscribe: createSubscribeApi(runtime),
  };
}
"#;

#[cfg(test)]
mod tests {
    use crate::{ir::ClientSpec, parser::parse_asyncapi};

    use super::TypeScriptGenerator;

    fn spec() -> ClientSpec {
        let input = r#"
asyncapi: 3.0.0
channels:
  telemetry:
    address: drones/{droneId}/telemetry
  command:
    address: drones/{droneId}/command
operations:
  sendTelemetry:
    action: send
    channel:
      $ref: '#/channels/telemetry'
  receiveCommand:
    action: receive
    channel:
      $ref: '#/channels/command'
messages:
  telemetry:
    payload:
      type: object
      required:
        - latitude
      properties:
        latitude:
          type: number
        longitude:
          type: number
  command:
    payload:
      type: object
      properties:
        command:
          type: string
"#;
        ClientSpec::from_document(&parse_asyncapi(input).expect("valid document"))
            .expect("valid spec")
    }

    #[test]
    fn generates_type_definitions() {
        let output = TypeScriptGenerator::types(&spec());

        assert!(output.contains("export type SendTelemetryPayload"));
        assert!(output.contains("latitude: number;"));
        assert!(output.contains("longitude?: number;"));
        assert!(output.contains("export type ReceiveCommandTopicParams"));
        assert!(output.contains("droneId: string | number | boolean;"));
    }

    #[test]
    fn generates_publish_methods() {
        let output = TypeScriptGenerator::client(&spec());

        assert!(output.contains("async sendTelemetry("));
        assert!(output.contains("runtime.publish(topic, payload"));
        assert!(output.contains("buildTopic(\"drones/{droneId}/telemetry\", params)"));
    }

    #[test]
    fn generates_subscribe_methods() {
        let output = TypeScriptGenerator::client(&spec());

        assert!(output.contains("receiveCommand("));
        assert!(output.contains("runtime.subscribe(\"drones/{droneId}/command\""));
        assert!(
            output.contains("handler: (payload: ReceiveCommandPayload, topic: string) => void")
        );
    }
}
