import type { ClientSpec, OperationSpec } from "../model/ir.js";
import { normalizeSchema } from "../schema/json-schema-to-typescript.js";
import { toPascalCase } from "../utils/case.js";

export function generateClient(spec: ClientSpec): string {
  return [
    "/* eslint-disable */",
    "// Generated by asyncapi-mqtt. Do not edit manually.",
    "",
    'import mqtt, { type IClientOptions, type IClientPublishOptions, type IClientSubscribeOptions, type MqttClient } from "mqtt";',
    'import Ajv, { type ValidateFunction } from "ajv";',
    generateTypeImports(spec),
    "",
    generateSchemas(spec),
    CLIENT_RUNTIME,
    generatePublishApi(spec),
    generateSubscribeApi(spec),
    CREATE_CLIENT_BLOCK,
  ].join("\n");
}

function generateTypeImports(spec: ClientSpec): string {
  const imports = spec.operations.flatMap((operation) => [
    `  ${toPascalCase(operation.name)}TopicParams,`,
    `  ${operation.payloadTypeName},`,
  ]);

  return ["import type {", ...imports, '} from "./types";'].join("\n");
}

function generateSchemas(spec: ClientSpec): string {
  const entries = spec.operations.map((operation) => {
    const schema = JSON.stringify(normalizeSchema(operation.payloadSchema), null, 2).replace(/\n/g, "\n  ");
    return `  ${operation.name}: ${schema},`;
  });
  return `const schemas = {\n${entries.join("\n")}\n} as const;\n`;
}

function generatePublishApi(spec: ClientSpec): string {
  const methods = spec.operations.filter((operation) => operation.action === "send").map(generatePublishMethod);
  return `function createPublishApi(runtime: ClientRuntime) {\n  return {\n${methods.join("")}  };\n}\n`;
}

function generatePublishMethod(operation: OperationSpec): string {
  return [
    `    async ${operation.name}(params: ${toPascalCase(operation.name)}TopicParams, payload: ${operation.payloadTypeName}, options: IClientPublishOptions = {}): Promise<void> {`,
    `      runtime.validate("${operation.name}", payload);`,
    `      const topic = buildTopic(${JSON.stringify(operation.topic.template)}, params);`,
    `      await runtime.publish(topic, payload, { qos: ${operation.qos ?? 0}, ...options });`,
    "    },",
    "",
  ].join("\n");
}

function generateSubscribeApi(spec: ClientSpec): string {
  const methods = spec.operations.filter((operation) => operation.action === "receive").map(generateSubscribeMethod);
  return `function createSubscribeApi(runtime: ClientRuntime) {\n  return {\n${methods.join("")}  };\n}\n`;
}

function generateSubscribeMethod(operation: OperationSpec): string {
  return [
    `    ${operation.name}(params: ${toPascalCase(operation.name)}TopicParams, handler: (payload: ${operation.payloadTypeName}, topic: string) => void, options: IClientSubscribeOptions = {}): () => void {`,
    `      return runtime.subscribe(${JSON.stringify(operation.topic.template)}, params, "${operation.name}", handler, { qos: ${operation.qos ?? 0}, ...options });`,
    "    },",
    "",
  ].join("\n");
}

const CLIENT_RUNTIME = `export type CreateClientOptions = {
  url: string;
  mqttOptions?: IClientOptions;
  validate?: boolean;
  ajv?: Ajv;
};

class ClientRuntime {
  private client?: MqttClient;
  private readonly ajv: Ajv;
  private readonly validators = new Map<string, ValidateFunction>();

  constructor(private readonly options: CreateClientOptions) {
    this.ajv = options.ajv ?? new Ajv();
  }

  async connect(): Promise<void> {
    if (this.client?.connected) {
      return;
    }

    this.client = mqtt.connect(this.options.url, this.options.mqttOptions);
    await new Promise<void>((resolve, reject) => {
      this.client?.once("connect", () => resolve());
      this.client?.once("error", reject);
    });
  }

  async end(): Promise<void> {
    if (!this.client) {
      return;
    }

    await new Promise<void>((resolve, reject) => {
      this.client?.end(false, {}, (error?: Error) => {
        if (error) {
          reject(error);
          return;
        }
        resolve();
      });
    });
    this.client = undefined;
  }

  validate(operationName: keyof typeof schemas, payload: unknown): void {
    if (this.options.validate === false) {
      return;
    }

    let validator = this.validators.get(operationName);
    if (!validator) {
      validator = this.ajv.compile(schemas[operationName]);
      this.validators.set(operationName, validator);
    }

    if (!validator(payload)) {
      throw new Error(\`Invalid payload for \${operationName}: \${this.ajv.errorsText(validator.errors)}\`);
    }
  }

  async publish(topic: string, payload: unknown, options: IClientPublishOptions): Promise<void> {
    const client = this.requireClient();
    await new Promise<void>((resolve, reject) => {
      client.publish(topic, JSON.stringify(payload), options, (error?: Error) => {
        if (error) {
          reject(error);
          return;
        }
        resolve();
      });
    });
  }

  subscribe<TPayload>(
    topicTemplate: string,
    params: Record<string, string | number | boolean>,
    operationName: keyof typeof schemas,
    handler: (payload: TPayload, topic: string) => void,
    options: IClientSubscribeOptions,
  ): () => void {
    const client = this.requireClient();
    const topic = buildTopic(topicTemplate, params);
    const listener = (receivedTopic: string, message: Buffer) => {
      if (receivedTopic !== topic) {
        return;
      }

      const payload = JSON.parse(message.toString()) as TPayload;
      this.validate(operationName, payload);
      handler(payload, receivedTopic);
    };

    client.on("message", listener);
    client.subscribe(topic, options);

    return () => {
      client.off("message", listener);
      client.unsubscribe(topic);
    };
  }

  private requireClient(): MqttClient {
    if (!this.client) {
      throw new Error("MQTT client is not connected. Call connect() first.");
    }
    return this.client;
  }
}

function encodeTopicParam(value: string | number | boolean): string {
  return encodeURIComponent(String(value));
}

function buildTopic(template: string, params: Record<string, string | number | boolean>): string {
  return template.replace(/\\{([^}]+)\\}/g, (_, key: string) => {
    if (!(key in params)) {
      throw new Error(\`Missing topic parameter: \${key}\`);
    }
    return encodeTopicParam(params[key]);
  });
}
`;

const CREATE_CLIENT_BLOCK = `export function createClient(options: CreateClientOptions) {
  const runtime = new ClientRuntime(options);

  return {
    connect: () => runtime.connect(),
    end: () => runtime.end(),
    publish: createPublishApi(runtime),
    subscribe: createSubscribeApi(runtime),
  };
}
`;
