import type { ClientSpec, OperationSpec } from "../model/ir.js";
import { jsonSchemaToTypeScript } from "../schema/json-schema-to-typescript.js";
import { toPascalCase } from "../utils/case.js";

export function generateTypes(spec: ClientSpec): string {
  const chunks = ["/* eslint-disable */", "// Generated by asyncapi-mqtt. Do not edit manually.", ""];

  for (const operation of spec.operations) {
    chunks.push(`export type ${toPascalCase(operation.name)}TopicParams = ${topicParamsType(operation)};`);
    chunks.push("");
    chunks.push(`export type ${operation.payloadTypeName} = ${jsonSchemaToTypeScript(operation.payloadSchema, 0)};`);
    chunks.push("");
  }

  return `${chunks.join("\n")}`;
}

function topicParamsType(operation: OperationSpec): string {
  if (operation.topic.parameters.length === 0) {
    return "Record<string, never>";
  }

  const fields = operation.topic.parameters
    .map((parameter) => `  ${parameter.name}: string | number | boolean;`)
    .join("\n");
  return `{\n${fields}\n}`;
}
